sudo: required
services:
    - docker


before_install:
    - docker build -t sagarpalnitkar/docker-react -f Dockerfile.dev .


script:
    - docker run sagarpalnitkar/docker-react npm run test -- --coverage